name: OpenClash Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up OpenClash
      run: |
        mkdir -p luci-app-openclash
        curl -L https://github.com/vernesong/OpenClash/archive/master.tar.gz | tar xz --strip-components=1 -C luci-app-openclash
        mkdir -p luci-app-openclash/root/etc/openclash/custom
        curl -fsSL https://raw.githubusercontent.com/shidahuilang/openwrt-package/usb/argon/openclash_custom_rules.list > luci-app-openclash/root/etc/openclash/custom/openclash_custom_rules.list
        #sed -i '/openclash.config.enable/{N;d;}' luci-app-openclash/root/etc/uci-defaults/luci-openclash

    - name: Commit and Push Changes
      run: |
        git config --local user.email "${{ secrets.USER_EMAIL }}"
        git config --local user.name "${{ secrets.USER_NAME }}"
        git add .
        git commit -m "Update OpenClash rules" || echo "No changes to commit"
        git push https://$REPO_TOKEN@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
